### ISSUE TITLE
🚀 [feature] DB 마이그레이션을 위한 flyway 도입

### ISSUE THREAD

**Issue by ahnsugyeong** [Team-Shaka/Briefing-Backend#200]
# 🤖 기능 개요
Briefing, Article간의 매핑 변동으로 인해 기존 데이터의 마이그레이션이 필요해졌습니다.
이 작업을 효율적으로 진행하기 위해 `Flyway`를 도입하여 DB 스키마 형상을 관리하고자 합니다.

## ✅ Todo
- [x] Flyway 의존성 추가
- [x] application.yml 설정
- [x] flyway 마이그레이션 스크립트 작성

### 📚 Remarks

- [[Briefing] Flyway로 DB 스키마 형상 관리하기 - 1](https://suddiyo.tistory.com/entry/Briefing-Flyway%EB%A1%9C-DB-%EC%8A%A4%ED%82%A4%EB%A7%88-%ED%98%95%EC%83%81-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0-1)
- [[Briefing] Flyway로 DB 스키마 형상 관리하기 - 2](https://suddiyo.tistory.com/entry/Briefing-Flyway%EB%A1%9C-DB-%EC%8A%A4%ED%82%A4%EB%A7%88-%ED%98%95%EC%83%81-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0-2)
