### ISSUE TITLE
🚀 [feature] 스크랩 기능 

### ISSUE THREAD

**Issue by swa07016** [Team-Shaka/Briefing-Backend#33]
# 🤖 기능 개요
기존 클라이언트에서 수행하던 스크랩 기능 로직을 서버로 가져옵니다.
## ✅ Todo
- [ ] Scrap 엔티티 생성 & 연관관계 세팅
- [ ] Scrap 조회 API
- [ ] Scrap 하기 / 취소하기 API
