### ISSUE TITLE
🚀 [feature] 브리핑 타입 구체화

### ISSUE THREAD

**Issue by swa07016** [Team-Shaka/Briefing-Backend#88]
# 🤖 기능 개요
- v2.0.0 기획에 따라 브리핑 타입을 구체화하고 연관 API들을 개발합니다. 

## ✅ Todo
- [ ] 브리핑 타입 구체화
- [ ] 브리핑 목록 조회 API
- [ ] 브리핑 단 건 조회 API
- GPT Model

### 📚 Remarks
- 앱 버전에 따라 API 요청, 응답이 조금씩 달라지는데 적절히 관리할 방안 찾기
- 아래 API는 2.0.0 릴리즈이전 release 브랜치로 단독 업데이트 해야할 수 있어서 다른 이슈로 생성하겠습니다.
    - 브리핑 등록 API
