### ISSUE TITLE
🚀 [feature] 브리핑 목록 조회 v2 수정사항

### ISSUE THREAD

**Issue by swa07016** [Team-Shaka/Briefing-Backend#90]
# 🤖 기능 개요
브리핑 목록 조회에서 날짜와 시간 쿼리 스트링 없이 분야만 포함했을 시, 최신 데이터를 내려줍니다.

## ✅ Todo
- [x] timeOfDay와 date 필수여부 false로 변경
- [x] CULTURE 타입 없애기
- [x] /v2/briefings?type=SOCIAL 처럼 요청시, 최신 10건 내려주기
